[package]
name = "gfacut"
version = "0.1.0"
authors = ["moinSebi <s.vorbrugg@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfaR = "0.1.2"
#gfaR = {path = "../gfaR"}